[build]
  command = "npm install --legacy-peer-deps && rm -rf apps/web/node_modules && npm run build --workspace=web"
  publish = "apps/web/.next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
