/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./{app,src,components}/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        black: 'popBlack',
        thin: 'popThin',
        reg: 'popReg',
        rare: 'popRare',
        homemade: 'popHomeMade',
      },
      fontSize: {
        'l-900': ['5rem', '5rem'],
        'l-800': ['4rem', '4rem'],
        'l-700': ['3.5rem', '3.5rem'],
        'l-600': ['2.5rem', '3rem'],
        'l-500': ['2rem', '2.5rem'],
        'l-400': ['1.5rem', '2rem'],
        'l-300': ['1.25rem', '1.75rem'],
        'l-200': ['1rem', '1.25rem'],
        'l-100': ['0.75rem', '1rem'],
        'l-button': ['0.875rem', '1.25rem'],
        'l-body': ['0.875rem', '1.25rem'],
        'l-caption': ['0.75rem', '1rem'],
        's-900': ['3.5rem', '3.5rem'],
        's-800': ['3rem', '3rem'],
        's-700': ['2.5rem', '2.5rem'],
        's-600': ['2rem', '2.25rem'],
        's-500': ['1.5rem', '1.75rem'],
        's-400': ['1.25rem', '1.5rem'],
        's-300': ['1.125rem', '1.5rem'],
        's-200': ['1rem', '1.5rem'],
        's-100': ['0.875rem', '1rem'],
        's-button': ['0.9375rem', '1.25rem'],
        's-body': ['0.9375rem', '1.25rem'],
        's-caption': ['0.8125rem', '1rem'],
      },
      colors: {
        greenlight: '#227432',
        greendark: '#224C22',
        orange: '#D17711',
        fresh: '#e6efe2',
        text: {
          DEFAULT: 'var(--text-default, #000)',
          subdued: 'var(--text-subdued, #8B8B84)',
          disabled: 'var(--text-disabled, #D8D8D2)',
          critical: 'var(--text-critical, #DE1037)',
          warning: 'var(--text-warning, #D58E2D)',
          success: 'var(--text-success, #0E5F2F)',
          highlight: 'var(--text-highlight, #382DCD)',
          'on-interactive': 'var(--text-on-interactive, #FFF)',
          'on-primary': 'var(--text-on-primary, #FFF)',
          'on-basic': 'var(--text-on-basic, #02010E)',
          'on-critical': 'var(--text-on-critical, #FFF)',
          'on-inverse': 'var(--text-on-inverse, #FFF)',
          'table-header-default': 'var(--text-table-header-default, #555F6D)',
        },
        icon: {
          DEFAULT: 'var(--text-default, #000)',
          subdued: 'var(--text-subdued, #8B8B84)',
          hovered: 'var(--text-hovered, #000)',
          pressed: 'var(--text-pressed, #000)',
          disabled: 'var(--text-disabled, #D8D8D2)',
          critical: 'var(--text-critical, #DE1037)',
          warning: 'var(--text-warning, #D58E2D)',
          success: 'var(--text-success, #0E5F2F)',
          highlight: 'var(--text-highlight, #382DCD)',
          'on-interactive': 'var(--text-on-interactive, #FFF)',
          'on-primary': 'var(--text-on-primary, #FFF)',
          'on-basic': 'var(--text-on-basic, #02010E)',
          'on-critical': 'var(--text-on-critical, #FFF)',
          'on-inverse': 'var(--text-on-inverse, #FFF)',
          'table-header-default': 'var(--text-table-header-default, #555F6D)',
        },
        interactive: {
          DEFAULT: 'var(--interactive-default, #4734FF)',
          hovered: 'var(--interactive-hovered, #3826E3)',
          pressed: 'var(--interactive-pressed, #2616C3)',
          disabled: 'var(--interactive-disabled, #7E8B99)',
        },
        'interactive-critical': {
          DEFAULT: 'var(--interactive-critical-default, #C53434)',
          hovered: 'var(--interactive-critical-hovered, #F26464)',
          pressed: 'var(--interactive-critical-pressed, #A13636)',
          disabled: 'var(--interactive-critical-disabled, #FCCFCF)',
        },
        'interactive-inverse': {
          DEFAULT: 'var(--interactive-inverse-default, #9F96F8)',
          hovered: 'var(--interactive-inverse-hovered, #8B82E3)',
          pressed: 'var(--interactive-inverse-pressed, #4A41A5)',
          disabled: 'var(--interactive-inverse-disabled, #8F8F8F)',
        },
        border: {
          DEFAULT: 'var(--border-default, #D8D8D2)',
          subdued: 'var(--border-subdued, #E4E4E0)',
          hovered: 'var(--border-hovered, #5F5F58)',
          depressed: 'var(--border-depressed, #5F5F58)',
          disabled: 'var(--border-disabled, #F3F3F1)',
          focused: 'var(--border-focused, #458FFF)',
        },
      },
    },
  },
  plugins: [],
};
