/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        black: 'popBlack',
        thin: 'popThin',
        reg: 'popReg',
      },
      colors: {
        greenlight: '#227432',
        greendark: '#224C22',
        orange: '#D17711',
        text: {
          DEFAULT: 'var(--text-default, #000)',
          subdued: 'var(--text-subdued, #8B8B84)',
          disabled: 'var(--text-disabled, #D8D8D2)',
          critical: 'var(--text-critical, #DE1037)',
          warning: 'var(--text-warning, #D58E2D)',
          success: 'var(--text-success, #0E5F2F)',
          highlight: 'var(--text-highlight, #382DCD)',
          'on-interactive': 'var(--text-on-interactive, #FFF)',
          'on-primary': 'var(--text-on-primary, #FFF)',
          'on-basic': 'var(--text-on-basic, #02010E)',
          'on-critical': 'var(--text-on-critical, #FFF)',
          'on-inverse': 'var(--text-on-inverse, #FFF)',
          'table-header-default': 'var(--text-table-header-default, #555F6D)',
        },
        icon: {
          DEFAULT: 'var(--text-default, #000)',
          subdued: 'var(--text-subdued, #8B8B84)',
          hovered: 'var(--text-hovered, #000)',
          pressed: 'var(--text-pressed, #000)',
          disabled: 'var(--text-disabled, #D8D8D2)',
          critical: 'var(--text-critical, #DE1037)',
          warning: 'var(--text-warning, #D58E2D)',
          success: 'var(--text-success, #0E5F2F)',
          highlight: 'var(--text-highlight, #382DCD)',
          'on-interactive': 'var(--text-on-interactive, #FFF)',
          'on-primary': 'var(--text-on-primary, #FFF)',
          'on-basic': 'var(--text-on-basic, #02010E)',
          'on-critical': 'var(--text-on-critical, #FFF)',
          'on-inverse': 'var(--text-on-inverse, #FFF)',
          'table-header-default': 'var(--text-table-header-default, #555F6D)',
        },
        interactive: {
          DEFAULT: 'var(--interactive-default, #4734FF)',
          hovered: 'var(--interactive-hovered, #3826E3)',
          pressed: 'var(--interactive-pressed, #2616C3)',
          disabled: 'var(--interactive-disabled, #7E8B99)',
        },
        'interactive-critical': {
          DEFAULT: 'var(--interactive-critical-default, #C53434)',
          hovered: 'var(--interactive-critical-hovered, #F26464)',
          pressed: 'var(--interactive-critical-pressed, #A13636)',
          disabled: 'var(--interactive-critical-disabled, #FCCFCF)',
        },
        'interactive-inverse': {
          DEFAULT: 'var(--interactive-inverse-default, #9F96F8)',
          hovered: 'var(--interactive-inverse-hovered, #8B82E3)',
          pressed: 'var(--interactive-inverse-pressed, #4A41A5)',
          disabled: 'var(--interactive-inverse-disabled, #8F8F8F)',
        },
        border: {
          DEFAULT: 'var(--border-default, #D8D8D2)',
          subdued: 'var(--border-subdued, #E4E4E0)',
          hovered: 'var(--border-hovered, #5F5F58)',
          depressed: 'var(--border-depressed, #5F5F58)',
          disabled: 'var(--border-disabled, #F3F3F1)',
          focused: 'var(--border-focused, #458FFF)',
        },
      },
    },
  },
  plugins: [],
};
